"""data table

Revision ID: 1e1cd3328c59
Revises: 
Create Date: 2020-05-19 14:54:33.721659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e1cd3328c59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('questions', sa.Text(length=30), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('password', sa.String(length=30), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('student', sa.Boolean(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('result_of_user_id', sa.Integer(), nullable=True),
    sa.Column('result_for_topic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['result_for_topic_id'], ['topic.id'], ),
    sa.ForeignKeyConstraint(['result_of_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topics_results_m2m_table',
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('results_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['results_id'], ['results.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topics_results_m2m_table')
    op.drop_table('results')
    op.drop_table('user')
    op.drop_table('topic')
    # ### end Alembic commands ###
